# Generated by Django 5.1.6 on 2025-05-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_conversation_closed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='closed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
